수업내용/1011/PJT/PJT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

수업내용/1011/PJT/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>", views.profile, name="profile"),
    path("userlist/", views.userlist, name="userlist"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
]

수업내용/1011/PJT/articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/comments/", views.comments_create, name="comments_create"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.comments_delete,
        name="comments_delete",
    ),
    path("<int:article_pk>/likes/", views.likes, name="likes"),
]

수업내용/1011/PJT/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_css %}
    {% block css %}{% endblock css %}
    <title>Movie Reviews</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark text-bg-dark p-0 p-lg-0">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'articles:index' %}">
                <img class="" src="{% static 'images/KPJSBY_Cinema.jpg' %}" alt="logo" height="60">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4 d-flex justify-content-between">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:userlist' %}">See userlist</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:profile' user.pk %}">welcome, {{ user }}</a>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'accounts:logout' %}" method="POST">
                            {% csrf_token %}
                            <input class="bg-dark border-0 nav-link" type="submit" value="Logout">
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">sign up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    {% bootstrap_javascript %}
    <footer class="text-center py-2">
        <div class="container sticky-bottom">
            <p>Web-django PJT, by KP</p>
        </div>
    </footer>
</body>

</html>