server/articles/urls.py
from django.urls import path
from articles import views

urlpatterns = [
    path("index/", views.index),
    path("dinner/", views.dinner),
    path("lotto/", views.lotto),
    path("isoddeven/<int:number>", views.isoddeven),
    path("calculator/<int:num1>/<int:num2>", views.calculator),
    path("yourname/", views.yourname),
    path("MBTI/", views.MBTI),
    path("kipsum/", views.kipsum),
    path("kipsumpage/", views.kipsumpage),
]

server/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", include("articles.urls")),
    path("practices/", include("practices.urls")),
    path("todos/", include("todos.urls")),
]

server/practices/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index),
]

server/todos/urls.py
from django.urls import path
from . import views

app_name = "todos"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("delete/<todo_id>", views.delete, name="delete"),
    path("completed/<todo_id>", views.complete, name="completed"),
]

server/todos/models.py
from django.db import models

# Create your models here.


class Todo(models.Model):
    content = models.CharField(max_length=80)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

server/articles/views.py
from django.shortcuts import render
import random

# Create your views here.


def index(request):
    context = {
        "name": "김광표",
        "img": "https://cdn.crowdpic.net/detail-thumb/thumb_d_063DE2526E75F644AA2AE4BD774FE330.jpg",
    }
    return render(request, "articles/index.html", context)


def dinner(request):
    pick = random.choice(list(range(4)))
    foods = [
        "족발",
        "햄버거",
        "치킨",
        "초밥",
    ]
    imgs = [
        "https://static.hubzum.zumst.com/hubzum/2019/07/26/11/8291a05e16b14e9b91eedc7a4375c934_780x585.jpg",
        "https://img.hani.co.kr/imgdb/resize/2017/0709/149948783091_20170709.JPG",
        "https://img.khan.co.kr/news/2021/05/09/l_2021051001000864600073041.jpg",
        "https://gurunavi.com/ko/japanfoodie/article/sushi/img/sushi_01.jpg",
    ]
    context = {
        "pick": foods[pick],
        "foods": foods,
        "img": imgs[pick],
    }

    return render(request, "articles/dinner.html", context)


def lotto(request):
    nums = list(map(str, range(1, 46)))
    lottonums = []
    win = [3, 11, 15, 20, 35, 44]
    bonus = 10
    for _ in range(1, 6):
        picknums = random.sample(nums, 7)
        mainnums = sorted(picknums[0:6], key=lambda x: int(x))
        bonusnum = picknums[6]
        cnt = 0
        for n in mainnums:
            if int(n) in win:
                cnt += 1
        rank = ""
        if cnt == 6:
            rank = " 1등 : 10억원!!!!!"
        elif cnt == 5:
            if bonusnum == bonus:
                rank = " 2등 : 5000만원!!!"
            else:
                rank = " 3등 : 150만원!!"
        elif cnt == 4:
            rank = " 4등 50000원!"
        elif cnt == 3:
            rank = " 5등 5000원"
        else:
            rank = " 꽝.. 다음 기회에!"
        lottonums.append(" ".join(mainnums) + " + " + str(bonusnum) + rank)
    context = {"lottonums": lottonums}
    return render(request, "articles/lotto.html", context)


def isoddeven(request, number):
    if number % 2 == 0:
        answer = "짝수"
    else:
        answer = "홀수"
    context = {"number": number, "answer": answer}
    return render(request, "articles/isoddeven.html", context)


def calculator(request, num1, num2):
    context = {
        "num1": num1,
        "num2": num2,
        "plus": num1 + num2,
        "minus": num1 - num2,
        "product": num1 * num2,
        "division": num1 // num2,
    }
    return render(request, "articles/calculator.html", context)


def yourname(request):
    return render(request, "articles/yourname.html")


def MBTI(request):
    mbtis = [["I", "E"], ["N", "S"], ["T", "F"], ["P", "J"]]
    yourmbti = ""
    for mbti in mbtis:
        yourmbti += random.choice(mbti)
    mbtiname = {
        "ISTJ": "청렴결백 논리주의자",
        "ISFJ": "용감한 수호자",
        "INTJ": "용의주도한 전략가",
        "INFJ": "선의의 옹호자",
        "ISTP": "만능 재주꾼",
        "ISFP": "호기심 많은 예술가",
        "INFP": "열정적인 중재자",
        "INTP": "논리적인 사색가",
        "ESTP": "모험을 즐기는 사업가",
        "ESFP": "자유로운 영혼의 연예인",
        "ENFP": "재기발랄한 활동가",
        "ENTP": "논쟁을 즐기는 변론가",
        "ESTJ": "엄격한 관리자",
        "ESFJ": "사교적인 외교관",
        "ENFJ": "정의로운 사회운동가",
        "ENTJ": "대담한 통솔자",
    }
    context = {
        "name": request.GET.get("name"),
        "yourmbti": yourmbti,
        "mbtiname": mbtiname[yourmbti],
    }
    return render(request, "articles/MBTI.html", context)


def kipsum(request):
    return render(request, "articles/kipsum.html")


def kipsumpage(request):
    paragraphs = request.GET.get("paragraphs")
    words = request.GET.get("words")
    yourparas = []
    klipsum = [
        "아니",
        "근데",
        "이건",
        "저는",
        "그러나,",
        "것",
        "하다.",
        "있다.",
        "나",
        "수",
        "않다.",
        "우리",
        "고기",
        "보다.",
        "더",
        "좋다.",
        "그리고,",
        "이",
        "경우",
        "좀",
        "인간",
        "사실",
        "신체",
        "소금",
        "생활",
        "새롭다.",
        "무엇일까?",
        "네,",
        "당연하다",
        "이미",
        "사용하다.",
        "왜?",
        "무엇을?",
        "어째서?",
        "지방",
        "현실",
        "먼저",
        "당신은",
        "불법",
        "비밀",
        "아니오!",
        "있는걸까?",
        "싫어!",
    ]
    for _ in range(int(paragraphs)):
        yourpara = ""
        for _ in range(int(words)):
            yourpara += random.choice(klipsum) + " "
        yourparas.append(yourpara)
    context = {
        "yourparas": yourparas,
    }
    return render(request, "articles/kipsumpage.html", context)

server/practices/views.py
from django.shortcuts import render

# Create your views here.
def index(request):

    return render(request, "practices/index.html")

server/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    _todos = Todo.objects.all().order_by("priority")
    context = {
        "todos": _todos,
    }
    return render(request, "todos/index.html", context)


def create(request):
    content = request.GET.get("formcontent")
    priority = request.GET.get("formpriority")
    deadline = request.GET.get("formdate")
    Todo.objects.create(content=content, priority=priority, deadline=deadline)
    return redirect("todos:index")


def delete(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    todo.delete()
    return redirect("todos:index")


def complete(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    todo.completed = not todo.completed
    todo.save()
    return redirect("todos:index")

server/articles/templates/articles/MBTI.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h2>{{ name }}님의 MBTI는</h2>
    <h1>{{ yourmbti }}</h1>
    <h1>{{ mbtiname }}입니다. </h1>
    <p>맞나요...?</p>
</body>

</html>

server/articles/templates/articles/calculator.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>계산이 어려운 당신을 위한 사칙연산 계산기</h1>
    <h1>{{ num1 }} + {{ num2 }} = {{ plus }}</h1>
    <h1>{{ num1 }} - {{ num2 }} = {{ minus }}</h1>
    <h1>{{ num1 }} * {{ num2 }} = {{ product }}</h1>
    <h1>{{ num1 }} // {{ num2 }} = {{ division }}</h1>

</body>

</html>

server/articles/templates/articles/dinner.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Today Dinner</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
    <div class="container">
        <h1 class="text-center py-4">오늘 저녁은 <span class="text-danger">{{ pick }}</span></h1>
        <div class="card">
            <img src="{{ img }}">
        </div>
        <p>메뉴판</p>
        <ul>
            {% for food in foods %}
            <li>{{ food }}</li>
            {% endfor %}
        </ul>
        <a href="/articles/dinner/" class="btn btn-primary">다른거 먹을래</a>
        <a href="/articles/index/" class="btn btn-primary">뒤로</a>
    </div>
</body>

</html>

server/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>{{ name }}님, </h1>
    <img src="{{ img }}" style="height: 10rem;">
    <br>
    <a href="/articles/dinner">오늘 저녁 뭐먹지??</a>
    <a href="/articles/lotto">로또 번호 추천 받기</a>
    <a href="/articles/yourname">나의 MBTI는?</a>
    <a href="/articles/kipsum">k-lorem ipsum 만들러 가기</a>
</body>

</html>

server/articles/templates/articles/isoddeven.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <p>{{ number }}은(는) {{ answer }} 입니다.</p>
</body>

</html>

server/articles/templates/articles/kipsum.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="/articles/kipsumpage/" method="GET">
        문단 수를 입력하세요 : <input type="text" name="paragraphs" id="paragraphs">
        <br>
        문단별 단어 수를 입력하세요 : <input type="text" name="words" id="words">
        <input type="submit" value="제출">
    </form>
</body>

</html>

server/articles/templates/articles/kipsumpage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>K-LIPSUM</h1>
    {% for yourpara in yourparas %}
    <div style="font-size: 1rem;">{{ yourpara }}</div>
    <br>
    {% endfor %}
</body>

</html>

server/articles/templates/articles/lotto.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>프로젝트</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
    <section class="container d-flex justify-content-center  py-5 m-5 bg-secondary text-white rounded-1">
        <div class="align-content-center d-flex flex-column">
            <h1 class="py-4">로또 추천 번호</h1>
            <a class="btn btn-secondary" href="/articles/lotto">다시 뽑기</a>
            <a class="btn btn-secondary" href="/articles/index">이전 페이지</a>
        </div>
    </section>
    <section class="container d-flex justify-content-center flex-column py-5 m-5 bg-secondary text-white rounded-1">
        {% for num in lottonums %}
        <div class="text-center m-1 py-1" style="font-size: 2rem;">{{ num }} </div>
        {% endfor %}
    </section>
    <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
</body>

</html>

server/articles/templates/articles/yourname.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="/articles/MBTI/" method="GET">
        이름을 입력하세요 : <input type="text" name="name" id="name">
        <input type="submit" value="제출">
    </form>
</body>

</html>

server/practices/templates/practices/index.html
{% extends 'base.html' %}

{% block content %}
<h1>검색 모음</h1>
<h2>Google</h2>
<form action="https://www.google.com/search">
    <input class="form-control" type="text" name="q">
    <input class="btn btn-primary" type="submit">
</form>
{% endblock %}

server/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, intial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body>
    <header></header>
    {% block content %}
    {% endblock %}
</body>

</html>

server/todos/templates/todos/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container d-flex justify-content-center flex-column">
    <img src="https://www.what-to-do.co.uk/wp-content/themes/whattodo/assets/svg/logo.svg">
    <form class="row g-1 d-flex justify-content-center" action="{% url 'todos:create' %}">
        <div class="col-5">
            <input class="form-control form-control-sm" type="text" name="formcontent" id="todotext" maxlength="80"
                placeholder="write to do" required>
        </div>
        <div class="col-2">
            <input class="form-control form-control-sm" type="number" name="formpriority" id="todopriority"
                maxlength="1" max="9" min="1" placeholder="priority" required>
        </div>
        <div class="col-auto" type="date">
            <input type="date" placeholder="deadline" name="formdate" required>
        </div>
        <div class="col-1">
            <input class="btn btn-primary btn-sm" type="submit" value="Add To-Do">
        </div>
    </form>
    <h2>To do list</h2>
    <table class="table table-warning table-bordered">
        <thead>
            <tr>
                <th scope="col">priority</th>
                <th scope="col">content</th>
                <th scope="col">deadline</th>
                <th scope="col">created_at</th>
                <th scope="col">Done?</th>
                <th scope="col">delete</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in todos %}
            {% if todo.completed == False %}
            <tr>
                <th scope="row" class="align-middle col-1">{{ todo.priority }}</th>
                <td class="align-middle col-5">{{ todo.content }}</td>
                <td class="align-middle col-2">{{ todo.deadline|timeuntil:todo.created_at }}</td>
                <td class="align-middle col-2">{{ todo.created_at }}</td>
                <td class="align-middle col-1">
                    <a class="btn btn-success" href="{% url 'todos:completed' todo.id %}">
                        Yes
                    </a>
                </td>
                <td class="align-middle col-1"><a class="btn btn-danger"
                        href="{% url 'todos:delete' todo.id %}">delete</a>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <h2>Done list</h2>
    <table class="table table-success table-bordered">
        <thead>
            <tr>
                <th scope="col">priority</th>
                <th scope="col">content</th>
                <th scope="col">deadline</th>
                <th scope="col">created_at</th>
                <th scope="col">back</th>
                <th scope="col">delete</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in todos %}
            {% if todo.completed == True %}
            <tr>
                <th scope="row" class="align-middle col-1">{{ todo.priority }}</th>
                <td class="align-middle col-5">{{ todo.content }}</td>
                <td class="align-middle col-2">{{ todo.deadline|timeuntil:todo.created_at }}</td>
                <td class="align-middle col-2">{{ todo.created_at }}</td>
                <td class="align-middle col-1">
                    <a class="btn btn-success" href="{% url 'todos:completed' todo.id %}">
                        Yes
                    </a>
                </td>
                <td class="align-middle col-1"><a class="btn btn-danger"
                        href="{% url 'todos:delete' todo.id %}">delete</a>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>
<footer class="text-center pb-3 text-secondary">created by KP</footer>
{% endblock %}