수업내용/1011/PJT/PJT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

수업내용/1011/PJT/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>", views.profile, name="profile"),
    path("userlist/", views.userlist, name="userlist"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
]

수업내용/1011/PJT/accounts/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

수업내용/1011/PJT/accounts/forms.py
# accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            "email",
            "first_name",
            "last_name",
        )

수업내용/1011/PJT/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
    update_session_auth_hash,
)
from django.contrib.auth.decorators import login_required
from .models import User

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            form.save()
            auth_login(request, user)
            return redirect("accounts:update")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("articles:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect("articles:index")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("articles:index")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        # form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("articles:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/change_password.html", context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("articles:index")


@login_required
def profile(request, pk):
    user = User.objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/profile.html", context)


@login_required
def userlist(request):
    users = User.objects.all()
    context = {
        "users": users,
    }
    return render(request, "accounts/userlist.html", context)

수업내용/1011/PJT/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container py-5">
    <h1 class="pb-3">password update</h1>
    <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
</div>
{% endblock content %}

수업내용/1011/PJT/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container">
    <h1>로그인</h1>
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="login">
    </form>
</div>
{% endblock content %}

수업내용/1011/PJT/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container  py-5">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title mb-3">My profile</h3>
            <h4 class="card-subtitle my-2">{{ user.username }}</h4>
            <p class="card-text">user no. {{ user.pk }}</p>
            <p class="card-text">{{ user.first_name }} {{ user.last_name }}</p>
            <p class="card-text">{{ user.email }}</p>
            <p class="card-text">joined at {{ user.date_joined|date:'Y-m-d H:i:s' }}</p>
        </div>
    </div>
    <div class="d-flex justify-content-end">
        <a class="btn btn-primary ms-3 my-3 end" href="{% url 'accounts:update' %}">update information</a>
        <a class="btn btn-primary ms-3 my-3 end" href="{% url 'accounts:change_password' %}">change password</a>
        <a class="btn btn-primary ms-3 my-3 end" href="{% url 'accounts:delete' %}">Delete account</a>
    </div>
</div>

{% endblock content %}

수업내용/1011/PJT/accounts/templates/accounts/signup.html
<!-- accounts/signup.html -->
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container p-5">
    <h1>Sign Up</h1>
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="submit">
    </form>
</div>
{% endblock content %}

수업내용/1011/PJT/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container py-5">
    <h1 class="pb-3">pofile detail</h1>
    <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_field form.email %}
        {% bootstrap_field form.first_name %}
        {% bootstrap_field form.last_name %}
        <input type="submit" value="submit">
    </form>

</div>
{% endblock content %}

수업내용/1011/PJT/accounts/templates/accounts/userlist.html
{% extends 'base.html' %}
{% block content %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<div class="container py-5">
    <div class="text-center">
        <h2>User list</h2>
    </div>
    {% for user in users %}
    <div class="card m-4">
        <div class="card-body">
            <h4 class="card-subtitle my-2">{{ user.username }}</h4>
            <p class="card-text">user no. {{ user.pk }}</p>
            <p class="card-text">joined at {{ user.date_joined|date:'Y-m-d H:i:s' }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}