수업내용/1011/PJT/PJT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

수업내용/1011/PJT/articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/comments/", views.comments_create, name="comments_create"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.comments_delete,
        name="comments_delete",
    ),
    path("<int:article_pk>/likes/", views.likes, name="likes"),
]

수업내용/1011/PJT/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=20)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,  related_name='like_articles')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to="images/", blank=True)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

수업내용/1011/PJT/articles/forms.py
from django import forms
from .models import Article
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "image"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = (
            "article",
            "user",
        )

수업내용/1011/PJT/articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Article, Comment
from .forms import ArticleForm
from .forms import ArticleForm, CommentForm

# Create your views here.


def index(request):
    articles = Article.objects.order_by("-pk")
    context = {"articles": articles}
    return render(request, "articles/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        article_form = ArticleForm(request.POST, request.FILES)
        if article_form.is_valid():
            article = article_form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect("articles:index")
    else:
        article_form = ArticleForm()
    context = {"article_form": article_form}
    return render(request, "articles/form.html", context=context)


@login_required
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    like = article.like_users.all()
    comment_form = CommentForm()
    comments = article.comment_set.all()
    context = {
        "article": article,
        "comment_form": comment_form,
        "comments": comments,
        "like": like,
    }
    return render(request, "articles/detail.html", context)


@login_required
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == "POST":
        article_form = ArticleForm(request.POST, request.FILES, instance=article)
        if article_form.is_valid():
            article_form.save()
            return redirect("articles:detail", article.pk)
    else:
        article_form = ArticleForm(instance=article)
    context = {
        "article_form": article_form,
    }
    return render(request, "articles/form.html", context)


@login_required
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect("articles:index")


@login_required
def comments_create(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment_form.save()
    return redirect("articles:detail", article.pk)


@login_required
def comments_delete(request, pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect("articles:detail", pk)


@login_required
def likes(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if article.like_users.filter(pk=request.user.pk).exists():
        # if request.user in article.like_users.all():
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
    return redirect("articles:detail", article_pk)

수업내용/1011/PJT/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container m-5">
    <div class="card">
        <h5 class="card-header">{{ article.title }}</h5>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                작성일 :
                {% if article.created_at == article.updated_at %}
                {{ article.created_at|date:"SHORT_DATETIME_FORMAT" }}
                {% else %}
                {{ article.updated_at|date:"y-m-d D" }} (수정됨)
                {% endif %}
            </li>
            <li class="list-group-item">글 번호 : {{ article.pk }}</li>
            <li class="list-group-item">작성자 : {{ article.user }}</li>
        </ul>
        <div class="card-body">
            {% if article.image %}
            <img src="{{ article.image.url }}" class="card-img-top my-2" alt="{{ article.image }}">
            {% endif %}
            <p class="card-text">{{ article.content }}</p>
        </div>
        <div class="text-center">
            <p>👍🏻 : {{ like|length }}</p>
        </div>
        <hr class="m-0">
        <div class="card-body d-flex justify-content-end">
            <form action="{% url 'articles:likes' article.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in article.like_users.all %}
                <input class="btn btn-info mx-2 text-white" type="submit" value="좋아요 취소">
                {% else %}
                <input class="btn btn-info mx-2 text-white" type="submit" value="좋아요">
                {% endif %}
            </form>
            <a class="btn btn-secondary" href="{% url 'articles:index' %}">홈으로</a>
            {% if request.user == article.user %}
            <a class="btn btn-primary" href="{% url 'articles:update' article.pk %}">수정</a>
            <a class="btn btn-danger" href="{% url 'articles:delete' article.pk %}">삭제</a>
            {% endif %}
        </div>
        <div class="card-footer">
            <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form comment_form %}
                <div class="text-end"><input class="btn btn-success" type="submit"></div>
            </form>
            <hr>
            <h4>댓글 ({{ comments|length }})</h4>
            <hr>
            <ul class="list-group list-group-flush">
                {% for comment in comments %}
                <li class="list-group-item align-middle">
                    <div class="d-flex justify-content-between">
                        <p class="card-text mx-2 py-3 my-0">{{ comment.user }}</p>
                        {% if request.user == comment.user %}
                        <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
                            {% csrf_token %}
                            <input class="text-danger border-0 text-decoration-none" type="submit" value="삭제">
                        </form>
                        {% endif %}
                    </div>
                    <div class="m-2">
                        {{ comment.content }}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

수업내용/1011/PJT/articles/templates/articles/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container m-5">
    {% if request.resolver_match.url_name == 'create' %}
    <h1> 글쓰기 </h1>
    {% else %}
    <h1> 수정하기 </h1>
    {% endif %}

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form article_form %}
        {% bootstrap_button button_type="submit" content="OK" %}
    </form>
</div>
{% endblock %}

수업내용/1011/PJT/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container m-5">
    <div class="text-center">
        <h1>이미지 포함 글 작성</h1>
        <div class="row">
            {% for article in articles %}
            <div class="col-4">
                <div class="card">
                    <a href="{% url 'articles:detail' article.pk %}">
                        {% if article.image %}
                        <img src="{{ article.image.url }}" class="card-img-top" alt="..." style="height: 10rem;">
                        {% else %}
                        <img src="{% static 'images/KPJSBY_Cinema.jpg' %}" class="card-img-top" alt="..."
                            style="height: 10rem;">
                        {% endif %}
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <p class="card-text">작성자 : {{ article.user }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% if request.user.is_authenticated %}
        <a class="btn btn-primary my-3 float-right" href="{% url 'articles:create' %}">글 쓰기</a>
        {% endif %}
    </div>

</div>
{% endblock %}